import { basename, resolve } from 'node:path'
import { readFileSync } from 'node:fs'

/**
 * Matches a full semantic version, per semver.org.
 */
const SEMVER_PATTERN =
  /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

/**
 * The npm package directory, which is the parent of the one holding these scripts.
 */
export const PACKAGE_ROOT = resolve(import.meta.dirname, '..')

/**
 * The repository root, which holds `proto` and the licence each package copies.
 */
export const REPO_ROOT = resolve(PACKAGE_ROOT, '..')

/**
 * The module `generate:version` writes, which the bindings read the schema version from.
 */
export const VERSION_MODULE = resolve(PACKAGE_ROOT, 'src', 'version.ts')

const SCRIPT_NAME = basename(process.argv[1] ?? 'script', '.ts')

/**
 * Reports why a script stopped and exits, so a caller never has to decide whether the failure was recoverable.
 */
export const fail = (reason: string): never => {
  console.error(`${SCRIPT_NAME}: ${reason}`)
  process.exit(1)
}

/**
 * Reads a text file with its line endings normalized and its edges trimmed.
 */
export const readText = (...segments: string[]): string => {
  return readFileSync(resolve(...segments), 'utf8')
    .replace(/\r\n/g, '\n')
    .trim()
}

/**
 * Reports whether a version is a semantic version.
 */
export const isSemanticVersion = (version: string): boolean => {
  return SEMVER_PATTERN.test(version)
}

/**
 * Reads the schema version the proto directory declares, which the generated bindings and any release have to agree with.
 * It must be a semantic version, since producers write it into `Lyric.version` where `validateLyric` demands exactly that.
 */
export const readSchemaVersion = (): string => {
  const version = readText(REPO_ROOT, 'proto', 'VERSION.txt')
  if (!isSemanticVersion(version)) {
    fail(`proto/VERSION.txt holds ${JSON.stringify(version)}, which is not a semantic version`)
  }
  return version
}

/**
 * Renders the version module for a schema version, so writing it and checking it stay the same statement.
 */
export const renderVersionModule = (version: string): string => {
  return `// Generated by script; do not edit.

/**
 * Version of the Protobuf schema these bindings were generated from.
 * Producers write it into \`Lyric.version\`.
 */
export const SCHEMA_VERSION = '${version}'
`
}
