import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const ROOT = import.meta.dirname
const SCHEMA_FILE = resolve(ROOT, '..', '..', 'proto', 'VERSION.txt')
const OUTPUT_FILE = resolve(ROOT, '..', 'src', 'version.ts')

const main = (): void => {
  const schema = readFileSync(SCHEMA_FILE, 'utf8').trim()
  if (!schema) {
    throw new Error(`empty version at ${SCHEMA_FILE}`)
  }

  const content = `// Generated by script; do not edit.

/**
 * Version of the Protobuf schema these bindings were generated from.
 * Producers write it into \`Lyric.version\`.
 */
export const SCHEMA_VERSION = '${schema}'
`

  writeFileSync(OUTPUT_FILE, content)
  console.log(`schema ${schema} -> src/version.ts`)
}

main()
